# Get all blog articles
GET http://localhost:3003/api/blogs
###

# Create new article Tester
POST http://localhost:3003/api/blogs
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InRlc3RlciIsImlkIjoiNjQ1ZTA1OWM0MzdlZmM4MDY3ODc4Yjc3IiwiaWF0IjoxNjgzODgzNDY0fQ.GzW23YOfjyfyWHeL9yCM3SOPMe4J07DHAcOq9qxj_7E

{
    "title": "Unit Testing with Jest and RTL",
    "author": "Tester",
    "url": "http://localhost:3003/api/blogs/19",
    "likes": 9
}
###

# Delete blog article Tester
DELETE http://localhost:3003/api/blogs/645deef6cd15a0f0aebef8cb
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InRlc3RlciIsImlkIjoiNjQ1ZTA1OWM0MzdlZmM4MDY3ODc4Yjc3IiwiaWF0IjoxNjgzODgzNDY0fQ.GzW23YOfjyfyWHeL9yCM3SOPMe4J07DHAcOq9qxj_7E
###

# Update an existing article Tester
PUT http://localhost:3003/api/blogs/645deef6cd15a0f0aebef8cb
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InRlc3RlciIsImlkIjoiNjQ1ZTA1OWM0MzdlZmM4MDY3ODc4Yjc3IiwiaWF0IjoxNjgzODgzNDY0fQ.GzW23YOfjyfyWHeL9yCM3SOPMe4J07DHAcOq9qxj_7E

{
    "title": "What is the Jamstack?",
    "author": "Tester",
    "url": "http://localhost:3003/api/blogs/13",
    "likes": 10
}
###
